<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'DURATION_NUMBER_VALIDATION_FAIL_{attribute}{min}{max}' => '{attribute} should be a decimal in range {min} - {max}',
    'ERROR' => 'Error',
    'JOB_STAT_NOT_EXIST' => 'Stat does not exists',
    'LOGIN_INCORRECT_USERNAME_OR_PASSWORD' => 'Incorrect username or password.',
    'NEW_PROJECT_OWNER_USER_NOT_FOUND' => 'Project owner not found.',
    'ONLY_PROJECT_OWNER_CAN_CHANGE_OWNER' => 'Only project owner can change owner',
    'ONLY_PROJECT_OWNER_CAN_DOWNGRADE_ROLE' => 'Only project owner can downgrade role',
    'ONLY_PROJECT_OWNER_CAN_REMOVE_ADMIN_USERS' => 'Only project owner can remove admin users',
    'OPERATION_NOT_FOUND' => 'Operation not found',
    'PROJECT_INVITE_EMAIL_ALREADY_TAKEN' => 'An invitation to {email} has already been sent.',
    'PROJECT_INVITE_ERROR_USER_ALREADY_INVITED_{email}' => 'User({email}) already registered as project member.',
    'PROJECT_INVITE_NOT_FOUND' => 'Invite not found',
    'PROJECT_INVITE_RESEND_INTERVAL_ERROR_{after}' => 'Please, retry after {after}',
    'PROJECT_INVITE_SAVE_ERROR_{email}' => 'Server error: invitation for {email} doesn\'t save',
    'PROJECT_INVITE_SERVER_ERROR_{email}' => 'Server error: user {email} could not register in project',
    'PROJECT_JOB_UNIQUE_ERROR' => 'This project already has a Job with the specified Key',
    'PROJECT_MANAGE_ACCESS_RESTRICTED' => 'You are not authorized to change this project',
    'PROJECT_NOT_FOUND' => 'Project not found.',
    'PROJECT_OWNER_UNREMOVABLE' => 'Project owner can not be removed.',
    'PROJECT_USER_NOT_FOUND' => 'Project member not found.',
    'PROJECT_VIEW_ACCESS_RESTRICTED' => 'You are not authorized to view this project.',
    'RESET_PASSWORD_USER_NOT_FOUND' => 'There is no user with e-mail address {email}.',
    'SECURE_KEY_ALREADY_USED' => 'This key has already been used.',
    'SECURE_KEY_EMAIL_ALREADY_USED' => 'This email address is already in use.',
    'SECURE_KEY_ERROR_USER_SAVING' => 'Can not update user.',
    'SECURE_KEY_NEW_KEY_ALREADY_ISSUED' => 'Key already requested. You can not request another key.',
    'SECURE_KEY_NOT_FOUND' => 'There is no entry for the specified key.',
    'SECURE_KEY_NOT_VALID' => 'Key has expired.',
    'SIGNUP_PASSWORDS_NOT_COMPARE' => 'Passwords are not equal!',
    'SOMETHING_WENT_WRONG' => 'Something went wrong..',
    'SUGNUP_EMAIL_ALREADY_USED' => 'This email address is already in use.',
    'USER_CANNOT_CHANGE_OWN_ROLE' => 'User cannot change own role.',
    'USER_NOT_A_PROJECT_MEMEBER' => 'This user is not a project member.',
    'USER_NOT_FOUND' => 'This user can not be found.',
];
