<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'DURATION_NUMBER_VALIDATION_FAIL_{attribute}{min}{max}' => '{attribute} должно быть числом в диапазоне от {min} до {max}',
    'ERROR' => 'Ошибка',
    'JOB_STAT_NOT_EXIST' => 'Статистика недоступна',
    'LOGIN_INCORRECT_USERNAME_OR_PASSWORD' => 'Неверное имя пользователя или пароль',
    'NEW_PROJECT_OWNER_USER_NOT_FOUND' => 'Пользователь не найден',
    'ONLY_PROJECT_OWNER_CAN_CHANGE_OWNER' => 'Только владелец проекта может назначать нового владельца',
    'ONLY_PROJECT_OWNER_CAN_DOWNGRADE_ROLE' => 'Только владелец проекта может понижать роль',
    'ONLY_PROJECT_OWNER_CAN_REMOVE_ADMIN_USERS' => 'Только владелец проекта может удалять администраторов',
    'OPERATION_NOT_FOUND' => 'Операция не найдена',
    'PROJECT_INVITE_EMAIL_ALREADY_TAKEN' => 'На этот E-mail уже было отправлено приглашение',
    'PROJECT_INVITE_ERROR_USER_ALREADY_INVITED_{email}' => 'Пользователь с email:{email} уже зарегистрирован в проекте',
    'PROJECT_INVITE_NOT_FOUND' => 'Приглашение не найдено',
    'PROJECT_INVITE_RESEND_INTERVAL_ERROR_{after}' => 'Повторная отправка приглашения возможна через {after}',
    'PROJECT_INVITE_SAVE_ERROR_{email}' => 'Ошибка сервера: приглашение для {email} не смогло сохраниться',
    'PROJECT_INVITE_SERVER_ERROR_{email}' => 'Ошибка сервера: пользователь {email} не смог зарегистрироваться в проекте',
    'PROJECT_JOB_UNIQUE_ERROR' => 'В данном проекте уже имеется задание с указанным идентификатором',
    'PROJECT_MANAGE_ACCESS_RESTRICTED' => 'У Вас нет прав на изменение данного проекта',
    'PROJECT_NOT_FOUND' => 'Проект не найден',
    'PROJECT_OWNER_UNREMOVABLE' => 'Невозможно удалить владельца проекта',
    'PROJECT_USER_NOT_FOUND' => 'Участник проекта не найден',
    'PROJECT_VIEW_ACCESS_RESTRICTED' => 'У Вас нет прав на просмотр данного проекта',
    'RESET_PASSWORD_USER_NOT_FOUND' => 'Пользователь с таким E-mail не найден, или был удалён',
    'SECURE_KEY_ALREADY_USED' => 'Этот ключ уже был использован ранее',
    'SECURE_KEY_EMAIL_ALREADY_USED' => 'Кто-то другой уже изменил свой e-mail адрес на тот, что вы указали',
    'SECURE_KEY_ERROR_USER_SAVING' => 'Ошибка обновления пользователя в БД',
    'SECURE_KEY_NEW_KEY_ALREADY_ISSUED' => 'Вы не можете использовать этот ключ, потому что уже запросили новый',
    'SECURE_KEY_NOT_FOUND' => 'Ключ не найден',
    'SECURE_KEY_NOT_VALID' => 'Срок действия ключа истёк, запросите новый',
    'SIGNUP_PASSWORDS_NOT_COMPARE' => 'Пароли не совпадают',
    'SOMETHING_WENT_WRONG' => 'Что-то пошло не так...',
    'SUGNUP_EMAIL_ALREADY_USED' => 'E-mail уже используется',
    'USER_CANNOT_CHANGE_OWN_ROLE' => 'Невозможно изменить роль самому себе',
    'USER_NOT_A_PROJECT_MEMEBER' => 'Пользователь не является участником проекта',
    'USER_NOT_FOUND' => 'Пользователь не найден',
];
